<?xml version="1.0" encoding="UTF-8"?><record_update table="sys_ui_message">
    <sys_ui_message action="INSERT_OR_UPDATE">
        <application/>
        <code/>
        <commented_message/>
        <key>task update failed on record {0} of table {1} with error: {2}</key>
        <language>uk</language>
        <message>Не вдалося оновити завдання на запис {0} таблиці {1} з помилкою: {2}</message>
        <sys_class_name>sys_ui_message</sys_class_name>
        <sys_created_by>bogdan.felinskyi</sys_created_by>
        <sys_created_on>2022-03-23 17:34:31</sys_created_on>
        <sys_id>d82e74231b96c910c069657bab4bcbdd</sys_id>
        <sys_mod_count>0</sys_mod_count>
        <sys_name>task update failed on record {0} of table {1} with error: {2}</sys_name>
        <sys_package display_value="I18N: Ukrainian Translations" source="176ebda287b38910f4b131570cbb3551">176ebda287b38910f4b131570cbb3551</sys_package>
        <sys_policy/>
        <sys_scope display_value="I18N: Ukrainian Translations">176ebda287b38910f4b131570cbb3551</sys_scope>
        <sys_update_name>sys_ui_message_d82e74231b96c910c069657bab4bcbdd</sys_update_name>
        <sys_updated_by>bogdan.felinskyi</sys_updated_by>
        <sys_updated_on>2022-03-23 17:34:31</sys_updated_on>
    </sys_ui_message>
</record_update>
